import { useState, useRef, useCallback } from "react";
import { scan as scanApi } from "../api";

/* ─── helpers ─── */
function conf(c) {
  if (c >= .85) return { lbl: "High",   cls: "ok"   };
  if (c >= .60) return { lbl: "Medium", cls: "warn" };
  return              { lbl: "Low",    cls: "bad"  };
}

function dlJSON(r) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:"application/json"}));
  a.download = "prescription.json"; a.click();
}

function dlCSV(r) {
  const hdr = ["Medicine","Strength","Dosage","Frequency","Duration","Confidence"];
  const rows = (r.medicines||[]).map(m=>[
    m.medicine_name,m.strength||"",m.dosage||"",m.frequency||"",
    m.duration||"",Math.round(m.confidence*100)+"%"
  ]);
  const csv = [hdr,...rows].map(row=>row.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(",")).join("\n");
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([csv],{type:"text/csv"}));
  a.download = "prescription.csv"; a.click();
}

function dlPDF(r) {
  const w = window.open("","_blank");
  const rows = (r.medicines||[]).map(m=>`<tr>
    <td style="padding:12px;border-bottom:1px solid #2d3748;color:#f8fafc"><b>${m.medicine_name}</b></td>
    <td style="padding:12px;border-bottom:1px solid #2d3748;color:#e2e8f0">${m.strength||"—"}</td>
    <td style="padding:12px;border-bottom:1px solid #2d3748;color:#e2e8f0">${m.dosage||"—"}</td>
    <td style="padding:12px;border-bottom:1px solid #2d3748;color:#e2e8f0">${m.frequency||"—"}</td>
    <td style="padding:12px;border-bottom:1px solid #2d3748;color:#a0aec0">${Math.round(m.confidence*100)}%</td>
  </tr>`).join("");
  w.document.write(`<!DOCTYPE html><html><head><title>Prescription Report</title></head>
  <body style="font-family:system-ui;max-width:800px;margin:40px auto;color:#f8fafc;background-color:#030712;padding:0 24px">
  <div style="border:1px solid #2d3748;padding:32px;border-radius:16px;background:rgba(13,20,38,0.6)">
    <h1 style="margin:0;font-size:2rem;letter-spacing:-0.03em;color:#10b981">Prescription Analysis Report</h1>
    <p style="color:#94a3b8;margin-top:6px;font-size:0.95rem">Generated by HealthMate AI · Overall confidence: ${Math.round((r.overall_confidence||0)*100)}%</p>
    <table style="width:100%;border-collapse:collapse;margin-top:32px">
      <thead>
        <tr style="background:rgba(255,255,255,0.03);text-align:left">
          <th style="padding:12px;border-bottom:1px solid #2d3748;color:#94a3b8">Medicine</th>
          <th style="padding:12px;border-bottom:1px solid #2d3748;color:#94a3b8">Strength</th>
          <th style="padding:12px;border-bottom:1px solid #2d3748;color:#94a3b8">Dosage</th>
          <th style="padding:12px;border-bottom:1px solid #2d3748;color:#94a3b8">Frequency</th>
          <th style="padding:12px;border-bottom:1px solid #2d3748;color:#94a3b8">Conf.</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>
    <p style="color:#64748b;font-size:11px;margin-top:40px;text-align:center;border-top:1px solid #2d3748;padding-top:16px">This report is for informational purposes only. Please consult your physician.</p>
  </div>
  </body></html>`);
  w.document.close(); w.print();
}

/* ─── icons ─── */
const IcoUp = () => <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>;
const IcoImg = () => <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>;
const IcoPDF = () => <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>;
const IcoChk = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>;
const IcoSend = () => <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>;
const IcoPapr = () => <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21.44 11.05l-9.19 9.19a6 6 0 01-8.49-8.49l9.19-9.19a4 4 0 015.66 5.66l-9.2 9.19a2 2 0 01-2.83-2.83l8.49-8.48"/></svg>;
const IcoSrch = () => <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>;

/* ─── field icons ─── */
const IcoPill = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 16.5c-1.5-1.5-2.5-3.5-2.5-6s1-4.5 2.5-6 3.5-2.5 6-2.5 4.5 1 6 2.5 2.5 3.5 2.5 6-1 4.5-2.5 6-3.5 2.5-6 2.5-4.5-1-6-2.5z"/><line x1="9" y1="9" x2="15" y2="15"/></svg>;
const IcoStrength = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>;
const IcoDose = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>;
const IcoClock = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>;
const IcoCalendar = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>;
const IcoInfo = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>;
const IcoAlert = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>;

export default function ScanSection({ user, onNeedAuth }) {
  const [file,    setFile]    = useState(null);
  const [preview, setPreview] = useState(null);
  const [result,  setResult]  = useState(null);
  const [loading, setLoading] = useState(false);
  const [error,   setError]   = useState("");
  const [over,    setOver]    = useState(false);
  const [msg,     setMsg]     = useState("");
  const fRef = useRef();

  const pick = useCallback(f => {
    if (!f) return;
    setFile(f); setPreview(URL.createObjectURL(f));
    setResult(null); setError("");
  }, []);

  const analyze = async () => {
    if (!file) return;
    setLoading(true); setError("");
    try { setResult(await scanApi.analyze(file)); }
    catch (e) { setError(e.message); }
    finally { setLoading(false); }
  };

  const reset = () => { setFile(null); setPreview(null); setResult(null); setError(""); setMsg(""); };

  const oc = result ? conf(result.overall_confidence || 0) : { lbl:"Low", cls:"bad" };

  return (
    <div className="app-shell">
      <div className="app-card">

        {/* ── body ── */}
        <div className="app-body">

          {loading ? (
            <div className="loading-container">
              {preview ? (
                <div className="scan-preview-container">
                  <img src={preview} alt="Scanning preview"/>
                  <div className="scan-glow-line" />
                </div>
              ) : (
                <div className="spinner"/>
              )}
              <p className="loading-msg">Analyzing your prescription details...</p>
            </div>

          ) : !result ? (
            /* upload state */
            <div style={{display:"flex",flexDirection:"column",alignItems:"center",width:"100%"}}>
              <div
                className={`upload-zone${over?" over":""}${preview?" has-file":""}`}
                onDragOver={e=>{e.preventDefault();setOver(true)}}
                onDragLeave={()=>setOver(false)}
                onDrop={e=>{e.preventDefault();setOver(false);pick(e.dataTransfer.files?.[0])}}
                onClick={()=>!preview && fRef.current?.click()}
              >
                {preview ? (
                  <div className="preview-wrap">
                    <img src={preview} alt="preview"/>
                    <button className="preview-rm" onClick={e=>{e.stopPropagation();reset()}}>Remove</button>
                  </div>
                ) : (
                  <>
                    <div className="up-circle"><IcoUp/></div>
                    <h3>Upload Your Prescription</h3>
                    <p>Drag &amp; drop your prescription here or <span>click to browse</span></p>
                    <div className="up-btns" onClick={e=>e.stopPropagation()}>
                      <button className="btn-up-fill"  onClick={()=>fRef.current?.click()}><IcoImg/> Upload Image</button>
                      <button className="btn-up-outline" onClick={()=>fRef.current?.click()}><IcoPDF/> Upload PDF</button>
                    </div>
                  </>
                )}
                <input ref={fRef} type="file" accept="image/*" hidden onChange={e=>pick(e.target.files?.[0])}/>
              </div>

              {file && !loading && (
                <div className="analyze-wrap">
                  <button className="btn-analyze" onClick={analyze}><IcoSrch/> Analyze Prescription</button>
                </div>
              )}
              {error && <div className="alert-err">{error}</div>}
            </div>

          ) : (
            /* results state */
            <div className="rx-wrap">
              <div className="rx-head">
                <div className={`rx-check ${oc.cls}`}><IcoChk/></div>
                <h2>Prescription Extracted</h2>
                <p>Overall confidence level: <strong>{Math.round((result.overall_confidence||0)*100)}%</strong></p>
              </div>

              {result.warnings?.length > 0 && (
                <div className="rx-warnings">
                  {result.warnings.map((w,i)=>(
                    <div key={i} className={`rx-warn ${w.severity==="high"?"h":w.severity==="medium"?"m":"l"}`}>
                      <strong>{w.type?.replace(/_/g," ")}</strong>
                      <p>{w.message}</p>
                    </div>
                  ))}
                </div>
              )}

              {result.medicines?.length > 0 ? (
                <div className="rx-cards-container">
                  {result.medicines.map((m,i)=>{
                    const mc = conf(m.confidence);
                    const fields = [
                      {l:"Medicine",    v:m.medicine_name,  c:m.confidence, icon: <IcoPill />},
                      m.strength     && {l:"Strength",      v:m.strength,    c:m.confidence, icon: <IcoStrength />},
                      m.dosage       && {l:"Dosage",         v:m.dosage,      c:m.confidence, icon: <IcoDose />},
                      m.frequency    && {l:"Frequency",      v:m.frequency,   c:m.confidence, icon: <IcoClock />},
                      m.duration     && {l:"Duration",       v:m.duration,    c:m.confidence, icon: <IcoCalendar />},
                      m.instructions && {l:"Instructions",   v:m.instructions,c:null, icon: <IcoInfo />},
                      m.common_use   && {l:"Common Use",     v:m.common_use,  c:null, icon: <IcoInfo />},
                      m.allergy_warning&&{l:"Allergy Warning",v:m.allergy_warning,c:null, icon: <IcoAlert />},
                      m.side_effects && {l:"Side Effects",   v:m.side_effects,c:null, icon: <IcoAlert />},
                    ].filter(Boolean);
                    return (
                      <div key={i} className="rx-card">
                        <div className="rx-card-head">
                          <span className="rx-num">#{i+1}</span>
                          <h3>{m.medicine_name}</h3>
                          <span className={`conf-badge ${mc.cls}`}>{Math.round(m.confidence*100)}% {mc.lbl}</span>
                        </div>
                        <div className="rx-med-grid">
                          {fields.map((f,fi)=>{
                            const fc = f.c != null ? conf(f.c) : null;
                            return (
                              <div key={fi} className="rx-grid-cell">
                                <div className="cell-header-wrap">
                                  <span className="cell-label">
                                    {f.icon}
                                    {f.l}
                                  </span>
                                  {fc ? (
                                    <span className={`conf-badge ${fc.cls}`}>{Math.round(f.c*100)}%</span>
                                  ) : (
                                    <span className="conf-badge info">Info</span>
                                  )}
                                </div>
                                <span className="cell-val">{f.v}</span>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="rx-empty">
                  <div className="rx-empty-icon"><IcoSrch/></div>
                  <h4>No Medicines Detected</h4>
                  <p>Try taking a clearer photo under good lighting.</p>
                </div>
              )}

              <div className="rx-export">
                <p className="rx-export-lbl">Export Scan Data</p>
                <div className="rx-export-btns">
                  {[["JSON",()=>dlJSON(result)],["CSV",()=>dlCSV(result)],["PDF",()=>dlPDF(result)]].map(([lbl,fn])=>(
                    <button key={lbl} className="rx-export-btn" onClick={fn}>
                      <IcoPDF/>{lbl}
                    </button>
                  ))}
                </div>
              </div>

              {result.raw_text && (
                <details className="rx-raw">
                  <summary><IcoPDF/>View extracted raw text</summary>
                  <pre>{result.raw_text}</pre>
                </details>
              )}

              <div className="rx-actions">
                <button className="btn-primary" onClick={reset}>Scan Another</button>
                <button className="btn-outline-sm" onClick={reset}>Back</button>
              </div>
            </div>
          )}
        </div>

        {/* ── message bar ── */}
        <div className="msg-bar">
          <button className="msg-attach" onClick={()=>fRef.current?.click()} title="Attach file"><IcoPapr/></button>
          <input className="msg-input" placeholder="Ask HealthMate AI about your prescription..."
            value={msg} onChange={e=>setMsg(e.target.value)}
            onKeyDown={e=>e.key==="Enter"&&file&&!loading&&analyze()}
          />
          <button className="msg-send" disabled={loading} onClick={file?analyze:()=>fRef.current?.click()}>
            <IcoSend/>
          </button>
        </div>
      </div>

      {/* disclaimer */}
      <p className="disclaimer-sm">
        This tool is meant for health information only. Please consult your doctor for any medical advice.
        {!user && <> <button onClick={onNeedAuth}>Sign in</button> to save your scan history.</>}
      </p>
    </div>
  );
}
