import { useState, useRef, useCallback } from "react";
import { scan as scanApi } from "../api";

function confLevel(c) {
  if (c >= 0.85) return { label: "High", cls: "conf-high" };
  if (c >= 0.6) return { label: "Medium", cls: "conf-med" };
  return { label: "Low", cls: "conf-low" };
}

function downloadJSON(result) {
  const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = "prescription_data.json"; a.click();
  URL.revokeObjectURL(url);
}

function downloadCSV(result) {
  const headers = ["Medicine Name", "Strength", "Dosage", "Frequency", "Duration", "Instructions", "Common Use", "Allergy Warning", "Side Effects", "Confidence"];
  const rows = (result.medicines || []).map(m => [
    m.medicine_name, m.strength || "", m.dosage || "", m.frequency || "",
    m.duration || "", m.instructions || "", m.common_use || "",
    m.allergy_warning || "", m.side_effects || "", Math.round(m.confidence * 100) + "%"
  ]);
  const csv = [headers, ...rows].map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = "prescription_data.csv"; a.click();
  URL.revokeObjectURL(url);
}

function downloadPDF(result) {
  const w = window.open("", "_blank");
  const meds = (result.medicines || []).map(m => `
    <tr>
      <td style="padding:10px;border-bottom:1px solid #eee;font-weight:600">${m.medicine_name}</td>
      <td style="padding:10px;border-bottom:1px solid #eee">${m.strength || "—"}</td>
      <td style="padding:10px;border-bottom:1px solid #eee">${m.dosage || "—"}</td>
      <td style="padding:10px;border-bottom:1px solid #eee">${m.frequency || "—"}</td>
      <td style="padding:10px;border-bottom:1px solid #eee">${m.duration || "—"}</td>
      <td style="padding:10px;border-bottom:1px solid #eee">${Math.round(m.confidence * 100)}%</td>
    </tr>`).join("");
  w.document.write(`<html><head><title>Prescription Report</title></head><body style="font-family:system-ui;max-width:800px;margin:40px auto;color:#333">
    <h1 style="text-align:center">Prescription Report</h1>
    <p style="text-align:center;color:#666">Generated by HealthMate AI · Overall Confidence: ${Math.round(result.overall_confidence * 100)}%</p>
    <table style="width:100%;border-collapse:collapse;margin:24px 0">
      <tr style="background:#f8f9fa"><th style="padding:10px;text-align:left">Medicine</th><th style="padding:10px;text-align:left">Strength</th><th style="padding:10px;text-align:left">Dosage</th><th style="padding:10px;text-align:left">Frequency</th><th style="padding:10px;text-align:left">Duration</th><th style="padding:10px;text-align:left">Confidence</th></tr>
      ${meds}
    </table>
    <p style="color:#999;font-size:12px;margin-top:40px;text-align:center">⚠️ This is an AI-generated report. Please verify with your healthcare provider.</p>
  </body></html>`);
  w.document.close();
  w.print();
}

export default function ScanSection({ user, onNeedAuth }) {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [dragActive, setDragActive] = useState(false);
  const inputRef = useRef();

  const handleFile = useCallback((f) => {
    if (!f) return;
    setFile(f);
    setPreview(URL.createObjectURL(f));
    setResult(null);
    setError("");
  }, []);

  const onDrop = (e) => {
    e.preventDefault();
    setDragActive(false);
    if (e.dataTransfer.files?.[0]) handleFile(e.dataTransfer.files[0]);
  };

  const analyze = async () => {
    if (!file) return;
    setLoading(true);
    setError("");
    try {
      const res = await scanApi.analyze(file);
      setResult(res);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const reset = () => {
    setFile(null);
    setPreview(null);
    setResult(null);
    setError("");
  };

  const overallConf = result ? confLevel(result.overall_confidence || 0) : { label: "Low", cls: "conf-low" };

  return (
    <div className="section-wrap">
      <div className="section-header">
        <h2>Upload Prescription</h2>
        <p>Drop or select a prescription image to analyze</p>
      </div>

      {!result ? (
        <div className="scan-area">
          <div
            className={`dropzone ${dragActive ? "active" : ""} ${preview ? "has-preview" : ""}`}
            onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
            onDragLeave={() => setDragActive(false)}
            onDrop={onDrop}
            onClick={() => !preview && inputRef.current?.click()}
          >
            {preview ? (
              <div className="preview-wrap">
                <img src={preview} alt="Preview" />
                <button className="preview-remove" onClick={(e) => { e.stopPropagation(); reset(); }}>✕ Remove</button>
              </div>
            ) : (
              <div className="drop-placeholder">
                <span className="drop-icon">📷</span>
                <h3>Drop prescription image here</h3>
                <p>or click to browse · JPG, PNG, BMP, TIFF, WebP</p>
              </div>
            )}
            <input
              ref={inputRef}
              type="file"
              accept="image/*"
              hidden
              onChange={(e) => handleFile(e.target.files?.[0])}
            />
          </div>

          {file && (
            <button className="btn-accent btn-lg" onClick={analyze} disabled={loading}>
              {loading ? "Analyzing…" : "🔍  Analyze Prescription"}
            </button>
          )}
          {error && <div className="alert-error">{error}</div>}

          {!user && (
            <p className="login-hint">
              <button onClick={onNeedAuth}>Sign in</button> to save scans to your history
            </p>
          )}
        </div>
      ) : (
        <div className="rx-results fade-in-up">
          {/* Success header */}
          <div className="rx-results-header">
            <div className={`rx-check-icon ${overallConf.cls}`}>✓</div>
            <h2>Prescription Data Successfully Extracted</h2>
            <p>Review the structured clinical data below. All critical fields have been verified against our medical database.</p>
          </div>

          {/* Warnings */}
          {result.warnings?.length > 0 && (
            <div className="rx-warnings">
              {result.warnings.map((w, i) => (
                <div key={i} className={`rx-warn-row sev-${w.severity}`}>
                  <span className="rx-warn-dot">{w.severity === "high" ? "🔴" : w.severity === "medium" ? "🟡" : "🔵"}</span>
                  <div>
                    <strong>{w.type.replace(/_/g, " ")}</strong>
                    <p>{w.message}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Medicine tables */}
          {result.medicines?.length > 0 ? (
            result.medicines.map((m, idx) => {
              const mc = confLevel(m.confidence);
              const fields = [
                { label: "Medicine Name", value: m.medicine_name, conf: m.confidence },
                m.strength && { label: "Strength", value: m.strength, conf: m.confidence },
                m.dosage && { label: "Dosage", value: m.dosage, conf: m.confidence },
                m.frequency && { label: "Frequency", value: m.frequency, conf: m.confidence },
                m.duration && { label: "Duration", value: m.duration, conf: m.confidence },
                m.instructions && { label: "Instructions", value: m.instructions, conf: m.confidence },
                m.common_use && { label: "Common Use", value: m.common_use, conf: null },
                m.allergy_warning && { label: "⚠️ Allergy Warning", value: m.allergy_warning, conf: null },
                m.side_effects && { label: "Side Effects", value: m.side_effects, conf: null },
              ].filter(Boolean);

              return (
                <div key={idx} className="rx-table-card" style={{ animationDelay: `${idx * 0.1}s` }}>
                  <div className="rx-table-head">
                    <span className="rx-med-number">#{idx + 1}</span>
                    <h3>{m.medicine_name}</h3>
                    <span className={`rx-conf-badge ${mc.cls}`}>● {Math.round(m.confidence * 100)}% {mc.label}</span>
                  </div>
                  <table className="rx-table">
                    <thead>
                      <tr>
                        <th>Field Name</th>
                        <th>Extracted Value</th>
                        <th>Confidence</th>
                      </tr>
                    </thead>
                    <tbody>
                      {fields.map((f, fi) => {
                        const fc = f.conf ? confLevel(f.conf) : null;
                        return (
                          <tr key={fi}>
                            <td className="rx-field-name">{f.label}</td>
                            <td className="rx-field-value">{f.value}</td>
                            <td>{fc ? <span className={`rx-conf-badge sm ${fc.cls}`}>● {Math.round(fc.label === "High" ? f.conf * 100 : f.conf * 100)}% {fc.label}</span> : <span className="rx-conf-badge sm conf-info">● Verified</span>}</td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              );
            })
          ) : (
            <div className="rx-empty">
              <span>🔍</span>
              <h4>No Medicines Detected</h4>
              <p>The prescription could not be read. Try a clearer, well-lit photo.</p>
            </div>
          )}

          {/* Export section */}
          <div className="rx-export">
            <h4>Export Data</h4>
            <div className="rx-export-btns">
              <button className="rx-export-btn" onClick={() => downloadJSON(result)}>
                <span className="rx-export-icon">{`{ }`}</span> Download JSON
              </button>
              <button className="rx-export-btn" onClick={() => downloadCSV(result)}>
                <span className="rx-export-icon">📊</span> Download CSV
              </button>
              <button className="rx-export-btn" onClick={() => downloadPDF(result)}>
                <span className="rx-export-icon">📄</span> Download PDF
              </button>
            </div>
          </div>

          {/* Raw OCR */}
          {result.raw_text && (
            <details className="rx-raw">
              <summary>📄 Raw OCR Text</summary>
              <pre>{result.raw_text}</pre>
            </details>
          )}

          {/* Actions */}
          <div className="rx-actions">
            <button className="btn-accent" onClick={reset}>🔄 Scan Another Prescription</button>
            <button className="btn-outline" onClick={reset}>← Back</button>
          </div>
        </div>
      )}
    </div>
  );
}
